name: mycart
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'
  

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5 
  connectivity_plus: ^6.0.2
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_svg: ^2.0.10+1
  flutter_rating_bar: ^4.0.0
  readmore: ^3.0.0
  google_maps_flutter: ^2.0.0
  intl: ^0.19.0
  country_code_picker: ^3.0.0
  country_picker: ^2.0.25
  nuts_activity_indicator: ^1.0.0
  flutter_staggered_grid_view: ^0.4.0
  swipe_refresh: ^1.1.1
  firebase_messaging: ^14.8.2
  onesignal_flutter: ^5.1.5
  sms_autofill: ^2.3.1
  in_app_review: ^2.0.9
  connection_notifier: ^2.0.1
  auth_buttons: ^3.0.2
  persistent_shopping_cart: ^0.0.7
  marquee: ^2.2.3
  cupertino_icons: ^1.0.6
  sizer: ^2.0.15
  carousel_slider: ^4.2.1
  firebase_core: ^2.30.1
  cloud_firestore: ^4.17.2
  tab_container: ^3.5.3
  animate_do: ^3.3.4
  getwidget: ^4.0.0
  awesome_dialog: ^2.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterBold.ttf
          weight: 700
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterBlackItalic.ttf
          weight: 900
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsBold.ttf
          weight: 700
